/* LINKs
0-Home
1-Solhidrex
2-Labinpina
3-Laxium
4-Dimenol
5-Diarrea
*/ 
export const data = [
   {
      Online:[
         {
            id:"Cafam",
            img:"/assets/img/Cafam.png",
            link:[
               "https://www.drogueriascafam.com.co/",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1121-comprar-en-cafam-pedialyte-60-con-zinc-frasco-con-500-ml-sabor-manzana-deshidratacion-precio-7501033957369.html",
               "https://www.drogueriascafam.com.co/dermocosmetica/10479-comprar-en-cafam-cetaphil-crema-hidratante-noche-caja-con-tarro-con-48-g-precio-3499320007979.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/9689-comprar-en-cafam-treda-polvo-3-g-caja-con-6-sobres-solucion-oral-precio-7702195205750.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1010-comprar-en-cafam-magnesia-tradicional-frasco-con-120-ml-antiacido-laxante-precio-7702057073930.html",
               "https://www.drogueriascafam.com.co/cuidado-personal/1336-comprar-en-cafam-medicasp-shampoo-caja-con-frasco-con-100-ml-caspa-precio-650240029158.html",
            ],
            width:"100%"
         },
         {
            id:"FarmaTodo",
            img:"/assets/img/Farmatodo.png",
            link:[
               "https://www.farmatodo.com.co/",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1121-comprar-en-cafam-pedialyte-60-con-zinc-frasco-con-500-ml-sabor-manzana-deshidratacion-precio-7501033957369.html",
               "https://www.drogueriascafam.com.co/dermocosmetica/10479-comprar-en-cafam-cetaphil-crema-hidratante-noche-caja-con-tarro-con-48-g-precio-3499320007979.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/9689-comprar-en-cafam-treda-polvo-3-g-caja-con-6-sobres-solucion-oral-precio-7702195205750.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1010-comprar-en-cafam-magnesia-tradicional-frasco-con-120-ml-antiacido-laxante-precio-7702057073930.html",
               "https://www.drogueriascafam.com.co/cuidado-personal/1336-comprar-en-cafam-medicasp-shampoo-caja-con-frasco-con-100-ml-caspa-precio-650240029158.html",
         ],
            width:"100%"
         },
         {
            id:"Pasteur",
            img:"/assets/img/Pasteur.png",
            link:[
               "https://www.farmaciaspasteur.com.co/",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1121-comprar-en-cafam-pedialyte-60-con-zinc-frasco-con-500-ml-sabor-manzana-deshidratacion-precio-7501033957369.html",
               "https://www.drogueriascafam.com.co/dermocosmetica/10479-comprar-en-cafam-cetaphil-crema-hidratante-noche-caja-con-tarro-con-48-g-precio-3499320007979.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/9689-comprar-en-cafam-treda-polvo-3-g-caja-con-6-sobres-solucion-oral-precio-7702195205750.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1010-comprar-en-cafam-magnesia-tradicional-frasco-con-120-ml-antiacido-laxante-precio-7702057073930.html",
               "https://www.drogueriascafam.com.co/cuidado-personal/1336-comprar-en-cafam-medicasp-shampoo-caja-con-frasco-con-100-ml-caspa-precio-650240029158.html",
            ],
            width:"100%"
         },
         {
            id:"LaRebaja",
            img:"/assets/img/LaRebaja.png",
            link:[
               "https://www.larebajavirtual.com/",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1121-comprar-en-cafam-pedialyte-60-con-zinc-frasco-con-500-ml-sabor-manzana-deshidratacion-precio-7501033957369.html",
               "https://www.drogueriascafam.com.co/dermocosmetica/10479-comprar-en-cafam-cetaphil-crema-hidratante-noche-caja-con-tarro-con-48-g-precio-3499320007979.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/9689-comprar-en-cafam-treda-polvo-3-g-caja-con-6-sobres-solucion-oral-precio-7702195205750.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1010-comprar-en-cafam-magnesia-tradicional-frasco-con-120-ml-antiacido-laxante-precio-7702057073930.html",
               "https://www.drogueriascafam.com.co/cuidado-personal/1336-comprar-en-cafam-medicasp-shampoo-caja-con-frasco-con-100-ml-caspa-precio-650240029158.html",
            ],
            width:"100%"
         },
         {
            id:"Colsubsidio",
            img:"/assets/img/Colsubsidio.png",
            link:[
               "https://www.drogueriascolsubsidio.com/",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1121-comprar-en-cafam-pedialyte-60-con-zinc-frasco-con-500-ml-sabor-manzana-deshidratacion-precio-7501033957369.html",
               "https://www.drogueriascafam.com.co/dermocosmetica/10479-comprar-en-cafam-cetaphil-crema-hidratante-noche-caja-con-tarro-con-48-g-precio-3499320007979.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/9689-comprar-en-cafam-treda-polvo-3-g-caja-con-6-sobres-solucion-oral-precio-7702195205750.html",
               "https://www.drogueriascafam.com.co/cuidado-digestivo/1010-comprar-en-cafam-magnesia-tradicional-frasco-con-120-ml-antiacido-laxante-precio-7702057073930.html",
               "https://www.drogueriascafam.com.co/cuidado-personal/1336-comprar-en-cafam-medicasp-shampoo-caja-con-frasco-con-100-ml-caspa-precio-650240029158.html",
            ],
            width:"100%"
         },
      ]
   },
   {
      Phisic:[
         {
            id:"Locatel",
            img:"/assets/img/Locatel.png",
            link:["","","","","","",]
         },
         {
            id:"LaEconomía",
            img:"/assets/img/LaEconomia.png",
            link:["","","","","","",]
         },
         {
            id:"CruzVerde",
            img:"/assets/img/CruzVerde.png",
            link:["","","","","","",]
         },
         {
            id:"Olimpica",
            img:"/assets/img/Olimpica.png",
            link:["","","","","","",]
         },
         {
            id:"La14",
            img:"/assets/img/La14.png",
            link:["","","","","","",]
         },
      ]
   },
]